//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Slot Engine
//  @ File Name : SlotEngine.cs
//  @ Date : 5/7/2014
//  @ Author : Evan McCall
//
//
#if UNITY_EDITOR
#endif
/// <summary>
/// Determines the logic used to build out the matrix. how to position and offset slots
/// </summary>
public enum eSlotShape
{
    None = -1,
    Square,
    Triangle,
    Hex,
    Count
}
