//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Slot Engine
//  @ File Name : FeaturesManager.cs
//  @ Date : 5/7/2014
//  @ Author : Evan McCall
//
//

namespace BoomSports.Prototype.Managers
{
	public class FeaturesManager
	{
		public Features activatedFeatures;
		
		/// <summary>
		/// Sets the options for the game to activate a specific feature
		/// </summary>
		/// <param name="Feature"></param>
		public void ActivateFeature(Features Feature)
		{
			
		}
	}
}