//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Slot Engine
//  @ File Name : StateManager.cs
//  @ Date : 5/7/2014
//  @ Author : Evan McCall
//
//

public static class StateManager
{
    public static States enCurrentState;
    public static States enCurrentMode;

    //State Switching Variables
    public delegate void StateDelegate(States State);
    public static event StateDelegate StateChangedTo;
    public static event StateDelegate StateSwitched;
    
    public delegate void SpinDelegate();
    public delegate void SpinStateChangedTo(SpinStates spinState);
    public static event SpinDelegate spin_activated_event;
    public static event SpinStateChangedTo spin_state_changed;
    //*************

    //Unity Functions

    //*********

    //State Manager Functions
    public static void SwitchState(States State)
    {
        enCurrentState = State;
        if(StateChangedTo != null)
            StateChangedTo.Invoke(State);
	}

    public static void SwitchStateSpin(States SlotEngineState)
    {
        SwitchState(SlotEngineState);
    }
}
