//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Slot Engine
//  @ File Name : Reel.cs
//  @ Date : 5/7/2014
//  @ Author : Evan McCall
//
//
using UnityEngine;
using System;
//TODO make conditional namespace - need to develop more
namespace BoomSports.Prototype
{
    /// <summary>
    /// Container for Target Conditional Reference
    /// </summary>
    [Serializable]
    public class TargetConditionalActiveContainer
    {
        /// <summary>
        /// Who should be the target - Refactor to make scriptable objects later - this is cash crossing specific
        /// </summary>
        [SerializeField]
        public TargetAnimatorTriggerSetOnActive[] targetsForConditionalTrue;
    }
}
