//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Slot Engine
//  @ File Name : WinConditions.cs
//  @ Date : 5/7/2014
//  @ Author : Evan McCall
//
//

using BoomSports.Prototype;
using System;
using UnityEngine;

[CreateAssetMenu(fileName = "WinningNodeCountEvaluationConditionObject", menuName = "BoomSportsScriptableObjects/WinningNodeCountEvaluationConditionScriptableObject", order = 4)]
[Serializable]
public class WinningNodeCountCondition : NodeEvaluationCondition
{
	/// <summary>
	/// Defines how many symbols are needed in the winning object to proceed
	/// </summary>
	[SerializeField]
	public int winningSymbolAmount;
	/// <summary>
	/// Evaluates if the condition was met
	/// </summary>
	/// <param name="winningObject">winningSymbols in the WinningObject as object</param>
	/// <returns></returns>
    public override bool EvaluateCondition(WinningObject winningObject, SuffixTreeNodeInfo nodeInfo)
    {
		if (winningObject.winningNodes.Length >= winningSymbolAmount)
        {
			return true;
        }
		else
        {
			return false;
        }
    }

    internal override bool EvaluateCondition(SuffixTreeNodeInfo suffixTreeNodeInfo)
    {
        throw new NotImplementedException();
    }

    internal override bool EvaluateCondition(SuffixTreeNodeInfo[] suffixTreeNodeInfo)
    {
        throw new NotImplementedException();
    }
}
