//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Slot Engine
//  @ File Name : SlotEngine.cs
//  @ Date : 5/7/2014
//  @ Author : Evan McCall
//
//
using System.Collections.Generic;

namespace Slot_Engine.Matrix.ScriptableObjects
{

    /// <summary>
    /// Defines a single symbol evaluation feature, Wilds - Overlays - Etc. returns list of nodes from configuration passed where symbol evaluates and conditions are met to trigger
    /// </summary>
    public abstract partial class SlotEvaluationScriptableObject : EvaluationScriptableObject
    {
        public readonly Features featureName;
        /// <summary>
        /// The name of the Symbol(s) targeted for the wild evaluation [SA01, MA01, Etc...]
        /// </summary>
        public string symbolTargetNames;
        /// <summary>
        /// List of symbols that meet criteria of conditions to activate
        /// </summary>
        public List<suffix_tree_node_info> symbolsActivatingEvaluationConditions;
    }
}
