//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Slot Engine
//  @ File Name : SlotEngine.cs
//  @ Date : 5/7/2014
//  @ Author : Evan McCall
//
//
using UnityEngine;

/// <summary>
/// Creates the scriptable object for Core Prefabs References to be set
/// </summary>
[CreateAssetMenu(fileName = "CorePrefabsReferenceObject", menuName = "BoomSportsScriptableObjects/CorePrefabsReferencesScriptableObject", order = 4)]
public class CorePrefabsReferencesScriptableObject : ScriptableObject
{
    /// <summary>
    /// The symbol weights object to draw from
    /// </summary>
    //public Transform symbolWeight;
}

