//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Slot Engine
//  @ File Name : Symbols.cs
//  @ Date : 5/7/2014
//  @ Author : Evan McCall
//
//


public enum Symbol {
	SA01,
	MA01,
	MI01,
	MI02,
	MI03,
	RO01,
	RO02,
	RO03,
	SA02,
	End
}
