//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Slot Engine
//  @ File Name : SlotEngine.cs
//  @ Date : 5/7/2014
//  @ Author : Evan McCall
//
//
using UnityEngine;

public abstract class BasePathTransformSpinEvaluatorScriptableObject : ScriptableObject
{
    /// <summary>
    /// Take the spin Time, path and times reached and and calculate position and return position 
    /// </summary>
    /// <param name="spinTimerCurrent"></param>
    /// <param name="startPositionInPath"></param>
    /// <param name="positionPath"></param>
    /// <param name="timesReachedEndOfPath"></param>
    /// <returns></returns>
    public abstract Vector3 EvaluateSpin(double spinTimerCurrent, ref SpinPath positionPath);
}
