//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Slot Engine
//  @ File Name : SlotEngine.cs
//  @ Date : 5/7/2014
//  @ Author : Evan McCall
//
//
using System;
using UnityEngine;

public partial class ReelStripSpinBaseScriptableObject : ScriptableObject
{

}

/// <summary>
/// Creates the scriptable object for the reels spin parameters
/// </summary>
[CreateAssetMenu(fileName = "ReelStripSpinParameters", menuName = "BoomSportsScriptableObjects/ReelStripSpinParametersScriptableObject", order = 2)]
public class ReelStripSpinDirectionalConstantScriptableObject : ReelStripSpinBaseScriptableObject
{
    /// <summary>
    /// Controls the direction of the spin
    /// </summary>
    [SerializeField]
    public Vector3 reel_spin_direction;
    /// <summary>
    /// Controls the spin speed during looping state
    /// </summary>
    [SerializeField]
    public float spin_speed_constant;
}