//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Slot Engine
//  @ File Name : SlotEngine.cs
//  @ Date : 5/7/2014
//  @ Author : Evan McCall
namespace Slot_Engine.Matrix.ScriptableObjects
{
    using System.Collections;
    using System.Collections.Generic;
    using UnityEngine;
    /// <summary>
    /// Creates the scriptable object for Core Prefabs References to be set
    /// </summary>
    [CreateAssetMenu(fileName = "StripSpinSettings", menuName = "BoomSportsScriptableObjects/StripSpinSettingsScriptableObject", order = 4)]
    public partial class StripSpinSettingsScriptableObject : BaseSpinSettingsScriptableObject
    {
        /// <summary>
        /// uses predefeined reelstrips to loop thru on spin loop
        /// </summary>
        public bool usePreDefinesStripsForLoop = false;
        /// <summary>
        /// This allows you to start spinning strips from the start of the strips array or the end
        /// </summary>
        public bool startSpinFirstInFirstOut = true;

        internal override int[] GetStopObjectOrder<T>(ref T[] objectCollection)
        {
            List<int> output = new List<int>();
            if (startSpinFirstInFirstOut)
            {
                for (int i = 0; i < objectCollection.Length; i++)
                {
                    output.Add(i);
                }
            }
            else
            {
                for (int i = objectCollection.Length-1; i >= 0; i--)
                {
                    output.Add(i);
                }
            }
            return output.ToArray();
        }
    }
}