//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Slot Engine
//  @ File Name : SlotEngine.cs
//  @ Date : 5/7/2014
//  @ Author : Evan McCall
//
//
using UnityEngine;
/// <summary>
/// Creates the scriptable object for the reels spin parameters
/// </summary>
[CreateAssetMenu(fileName = "ReelStripSpinStepperParameters", menuName = "BoomSportsScriptableObjects/ReelStripSpinParametersScriptableObject", order = 2)]
public partial class StripSpinDirectionalStepperEvaluatorScriptableObject : StripSpinEvaluatorBaseScriptableObject
{
    /// <summary>
    /// Controls the spin speed during looping state
    /// </summary>
    [SerializeField]
    public float spin_speed_constant;
}