//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Slot Engine
//  @ File Name : SlotEngine.cs
//  @ Date : 5/7/2014
//  @ Author : Evan McCall
//
//
using UnityEngine;

public abstract class StripSpinEvaluatorBaseScriptableObject : BasePathTransformSpinEvaluatorScriptableObject
{//Needs to be abstract and every new scriptable object needs to evaluate vector 3 to from and percent along path to return slots spin value
    /// <summary>
    /// Controls the direction of the spin
    /// </summary>
    [SerializeField]
    public Vector3 reel_spin_direction;
}
