//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Slot Engine
//  @ File Name : SlotEngine.cs
//  @ Date : 5/7/2014
//  @ Author : Evan McCall
//
//
using UnityEngine;
using WeightedDistribution;

[CreateAssetMenu(fileName = "WeightsDistribution", menuName = "BoomSportsScriptableObjects/WeightsDistributionScriptableObject", order = 5)]
public class WeightsDistributionScriptableObject : ScriptableObject
{
    /// <summary>
    /// The symbol weights object to draw from
    /// </summary>
    public IntDistribution intDistribution;
}

